# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38ba15e0b1d2a8c2ff531a2056e7f5cb4274c0ea20ab2c419bc8fe410db66417be4481a98e1e0c88c019be3f98a75636027d968aa6c2f5d8046eb16b70278273

test:
  secret_key_base: e56ed8b07b5b75f053938fefaf3beba8476ff7ca2157b4623a2a6d64287cadb99a04cc84dc8abf00a0bcc66f4cfa947c62e5c86c07dc2f284cc79afcab862c9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
